#!/usr/bin/env bash

if [ $1 = "stop" ]
then
    cd Api/.docker/ && docker-compose stop
elif [ $1 = "start" ]
then
    cd Api/.docker/ && docker-compose up -d
elif [ $1 = "workspace" ]
then
    cd Api/.docker/ && docker-compose exec --user=laradock workspace bash
fi
